### PR TITLE
Add recently used envelopes bar

### PR DESCRIPTION
**Pull request by hobinjk-ptc**

### CODE REVIEW

**Review by benptc — APPROVED** [review]
Very slick! LGTM!

**Comment by benptc** [comment]
I didn't test this on iOS yet, and I can imagine we might have some issues with responsive design if the screen is too small, but that's something we can polish later

**Comment by hobinjk-ptc** [comment]
Oh, good point! I'll do a quick test to make sure it isn't unbearable

**Comment by hobinjk-ptc** [comment]
Could be better but I'm declaring it a good point from which to improve

**Pull request merged**
