### PR TITLE
Single layer grid

### PR DESCRIPTION
**Pull request by ptc-rdeleeuw**
simplify the render loop by eliminating the need for layers, rendering the whole scene at once instead of multiple times with different layers

depends on:
https://github.com/ptcrealitylab/vuforia-spatial-remote-operator-addon/pull/158

### CODE REVIEW

**Review by Steve-KX-RL — COMMENTED** [review]
LGTM. Is there any reason why we set up layers in the past?

**Review by hobinjk-ptc — CHANGES_REQUESTED** [review]
Very promising technique for resolving the issues we currently use layers for, nice work! Unfortunately, the use of layers in rendering is not only limited to the ground plane grid. We also use them to enable the point cloud rendering to draw above the scan (there used to be some more complex techniques in use as well (the stenciling work) but for our current visuals just drawing above would be sufficient). See attached screenshots for a comparison:
Screenshot 2024-03-06 at 10 52 49 AM

Screenshot 2024-03-06 at 10 52 31 AM

**Comment by ptc-rdeleeuw** [comment]
The main reason for this change is that webxr mode hardcodes layer 1 to the left eye and layer 2 to the right eye, layer 0 (default) renders to both eyes. Where can I find this point cloud rendering code? I would like to make that layer-less as well.

**Comment by hobinjk-ptc** [comment]
For sure! I agree that that's a good goal.

https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/blob/main/src/spatialCapture/Shaders.js is the source. Some examples of how the exports of this file are used: https://github.com/ptcrealitylab/vuforia-spatial-remote-operator-addon/blob/main/content_scripts/CameraVis.js is the real-time live streaming and https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/blob/main/src/spatialCapture/CameraVisPatch.js is the static captures.

**Review by benptc — APPROVED** [review]
This seems like a good optimization. LGTM so far.

@Steve-KX-RL has also modified the TransformControls to work with our layers (not really used at the moment but will likely be used in future for moving 3D content around more easily). Steve, would the TransformControls still work without the layers?
https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/blob/single_layer_grid/thirdPartyCode/three/TransformControls.js

**Comment by Steve-KX-RL** [comment]
> This seems like a good optimization. LGTM so far.
> 
> @Steve-KX-RL has also modified the TransformControls to work with our layers (not really used at the moment but will likely be used in future for moving 3D content around more easily). Steve, would the TransformControls still work without the layers? https://github.com/ptcrealitylab/vuforia-spatial-toolbox-userinterface/blob/single_layer_grid/thirdPartyCode/three/TransformControls.js

It would need some minor tweaking but still works. We can always re-enable some optional layers if we only want to pick specific stuff.

**Comment by ptc-rdeleeuw** [comment]
For spatial photo/video I've used the render order to fix the issue.
- first we render the scanned background
- then we disable the depth test, and render the pointcloud (depth only), this will overwrite the background depth values, ignoring them during the rest of the render
- finally we render all the elements in the scene (without the back ground) including the pointclouds for color and depth checking

**Comment by ptc-rdeleeuw** [comment]
Layer 10 will contain additional gltf models in the future but is not currently in use so we can delay solving that issue until work on that feature is continued

**Review by Steve-KX-RL — APPROVED** [review]
LGTM, thx Rik!

**Review by hobinjk-ptc — APPROVED** [review]

**Pull request merged**
