### PR TITLE
Alter three's updateMatrixWorld to not touch hidden objects

### PR DESCRIPTION
**Pull request by hobinjk-ptc**
Significantly improves the performance of updateMatrixWorld, previously a large contributor to frame time.

### CODE REVIEW

**Comment by dangond-ptc** [comment]
How does this change work if you change the matrices of something that is invisible and then make it visible? Is this ever a problem?

**Comment by hobinjk-ptc** [comment]
As far as I can tell what will happen is the object's matrices will then be calculated on the frame that it becomes visible

**Comment by dangond-ptc** [comment]
> As far as I can tell what will happen is the object's matrices will then be calculated on the frame that it becomes visible

Oh, that's perfect then!

**Comment by dangond-ptc** [comment]
Only problem I can see is that if we ever update three in the future, we might need to re-apply this change

**Comment by hobinjk-ptc** [comment]
Yeah, luckily it's one line, otherwise I'd be much more inclined to do this correctly with a fork and all that nonsense (which would still be its own minor nightmare)

**Pull request merged**
